#!/opt/sdr/report/perl/bin/perl -w

### vars
my $ws = "/opt/sdr/report/ws";
my $outf  = "htpasswd";

if (! scalar @ARGV ) {
  print "Usage: htpasswd user password\n";
  print "Note: this automatically creates the tile, if needed\n";
  exit 0;
}

@saltsource = ('a'..'z', 'A'..'Z', '0'..'9','.','/');
$randum_num = int(rand(scalar @saltsource));
$salt = $saltsource[$randum_num];
$randum_num = int(rand(scalar @saltsource));
$salt .= $saltsource[$randum_num];

$user=$ARGV[0];
$passwd=$ARGV[1];

if ($user && $passwd) {
    $encrypted = crypt($passwd, "$salt");

    if (-f $outf) {
        open(OUT, ">>$ws/conf/$outf") || die "htpasswd error: $!\n";
    } else {
        open(OUT, ">$ws/conf/$outf") || die "htpasswd error: $!\n";
    }
    
    print OUT "$user:$encrypted\n";
    close(OUT);

exit 0;
}
